name: Telegram Test

on:
  workflow_dispatch:

jobs:
  send-telegram-message:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install python-telegram-bot
        run: pip install python-telegram-bot==13.15

      - name: Send test message
        run: |
          python -c "
import os
import telegram

token = os.getenv('TELEGRAM_TOKEN')
chat_id = os.getenv('CHAT_ID')

if not token or not chat_id:
    raise Exception('TELEGRAM_TOKEN oder CHAT_ID nicht gesetzt.')

bot = telegram.Bot(token=token)
bot.send_message(chat_id=chat_id, text='Testnachricht vom GitHub Bot')
print('✅ Nachricht gesendet.')
"
